### ISSUE TITLE
Whats the purpose of changing the OneShotScheduler priority?

### ISSUE THREAD

**Issue by ritchiewilson** [abrauchli/shotwell#3]
Hey, I've been in the process of stripping down your maps code in the hope of getting it merged into shotwell. One minor detail I'm looking through is what is the purpose of changing the scheduler priorities so that they are higher priority than Clutter?

https://github.com/abrauchli/shotwell/blob/libchamplain/src/util/misc.vala#L284

Is there any specific scheduler that breaks if it is just set to DEFAULT_IDLE? What does this fix?

Also, thanks so much for the awesome code. It's a pleasure to work on.

**Comment by abrauchli** [comment]
Hey Ritchie,

sorry for the delay and thanks for the kind words on the code.

The original idea behind changing the priority is to fix the slow
imports due to the map panning. When the map is panning over to another
point, the UI becomes unresponsive until the pan is finished because
libchamplain's panning algorithm is using the same queue (gobject) w/ a
higher priority than what shotwell uses for imports. This causes
extremely slow imports w/ up to 2-3s delay in between each geocoded
picture.
The code did work when I tested it, however, I did notice that it
doesn't anymore - since quite some time. I tried adapting the priorities
without much success and, honestly, haven't spent too much time on it.

The first thing to do would be to check whether libchamplain still uses
this queue and simply changed its priority for the map panning
(probably). That would be hardcoded. Then set shotwell at higher
priority (out of my head I'm not sure if that means a higher or lower
priority number.)

Thanks for checking out the code, I'd be happy to merge back any
progress and answer further questions.
- andy

**Comment by ritchiewilson** [comment]
Yeah, obviously no worries with your delay. I get to shotwell myself when I have free time. :)

And thanks for the info. In the stripped down version I have, the map is only enabled in certain modes, basically single photo mode. So my solution was just to disable the map during imports. But that's really helpful to know that the map can steal priority if not watched.
